blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/joogiebear/webstack-installer/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/joogiebear/webstack-installer/wiki
    about: Read the documentation and guides
